const source_languages = [
  {label: 'Any (detect)', value: 'DTC'},
  {label: 'Bulgarian', value: 'BG'},
  {label: 'Chinese', value: 'ZH'},
  {label: 'Czech', value: 'CS'},
  {label: 'Danish', value: 'DA'},
  {label: 'Dutch', value: 'NL'},
  {label: 'English', value: 'EN'},
  {label: 'Estonian', value: 'ET'},
  {label: 'Finnish', value: 'FI'},
  {label: 'French', value: 'FR'},
  {label: 'German', value: 'DE'},
  {label: 'Greek', value: 'EL'},
  {label: 'Hungarian', value: 'HU'},
  {label: 'Italian', value: 'IT'},
  {label: 'Japanese', value: 'JA'},
  {label: 'Latvian', value: 'LV'},
  {label: 'Lithuanian', value: 'LT'},
  {label: 'Polish', value: 'PL'},
  {label: 'Portuguese', value: 'PT'},
  {label: 'Romanian', value: 'RO'},
  {label: 'Russian', value: 'RU'},
  {label: 'Slovak', value: 'SK'},
  {label: 'Slovenian', value: 'SL'},
  {label: 'Spanish', value: 'ES'},
  {label: 'Swedish', value: 'SV'},
];

const target_languages = [
  {label: 'Bulgarian', value: 'BG'},
  {label: 'Chinese', value: 'ZH'},
  {label: 'Czech', value: 'CS'},
  {label: 'Danish', value: 'DA'},
  {label: 'Dutch', value: 'NL'},
  {label: 'English (US)', value: 'EN-US'},
  {label: 'English (GB)', value: 'EN-GB'},
  {label: 'Estonian', value: 'ET'},
  {label: 'Finnish', value: 'FI'},
  {label: 'French', value: 'FR'},
  {label: 'German', value: 'DE'},
  {label: 'Greek', value: 'EL'},
  {label: 'Hungarian', value: 'HU'},
  {label: 'Italian', value: 'IT'},
  {label: 'Japanese', value: 'JA'},
  {label: 'Latvian', value: 'LV'},
  {label: 'Lithuanian', value: 'LT'},
  {label: 'Polish', value: 'PL'},
  {label: 'Portuguese', value: 'PT-PT'},
  {label: 'Portuguese (BR)', value: 'PT-BR'},
  {label: 'Romanian', value: 'RO'},
  {label: 'Russian', value: 'RU'},
  {label: 'Slovak', value: 'SK'},
  {label: 'Slovenian', value: 'SL'},
  {label: 'Spanish', value: 'ES'},
  {label: 'Swedish', value: 'SV'},
];

export { source_languages, target_languages };